services:
  postgres:
    image: postgres:latest
    container_name: postgres-tv-looker
    restart: always
    environment:
      POSTGRES_USER: tv-looker-admin
      POSTGRES_PASSWORD: this-is-a-super-secure-password123
      POSTGRES_DB: tv-looker-db
    ports:
      - "5432:5432"
